project_name: actions-demo

before:
  hooks:
    - make generate
builds:
  - main: ./cmd/actions-demo/main.go
    binary: bin/actions-demo
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
dockers:
  -
    image_templates:
    - "jonwhit/actions-demo:{{ .Tag }}"
    - "jonwhit/actions-demo:v{{ .Major }}"
    - "jonwhit/actions-demo:v{{ .Major }}.{{ .Minor }}"
    - "jonwhit/actions-demo:latest"
    - "gcr.io/jon-whit/actions-demo"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
