name: go-test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: src/github.com/jon-whit/actions-demo
      
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
      
      - name: Setup GOPATH
        run: |
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
          echo $(go evn GOBIN) >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          go install ./...

      - name: Vet and Lint
        run: |
          go vet ./...
          golint -set_exit_status ./...

      - name: Go Test
        run: |
          go test ./...